Repository OWASP/wstg, pull requests merged in 2019-05, with the labels that each got.

#53 Create PR Template
  .github/pull_request_template.md
Labels: New, Repo

#55 Add Label to fix-request issue template
  .github/ISSUE_TEMPLATE/fix-request.md
Labels: Repo

#49 Create 4.8.18 Testing for Host Header Injection (OTG-INPVAL-018).md
  document/4 Web Application Security Testing/4.8 Input Validation Testing/4.8.18 Testing for Host Header Injection (OTG-INPVAL-018).md
Labels: waiting-for:pr-author

#58 New content 4.3.10 Test for subdomain takeover (OTG-CONFIG-010)
  document/4 Web Application Security Testing/4.3 Configuration and Deployment Management Testing/4.3.10 Test for subdomain takeover (OTG-CONFIG-010).md
  document/4 Web Application Security Testing/images/subdomain_takeover_ex1.jpeg
  document/4 Web Application Security Testing/images/subdomain_takeover_ex2.jpeg
Labels: New

#60 Section 1 Changes for v5
  document/1 Frontispiece/1 Frontispiece.md
  document/Appx.E Misc/AppxE History.md
Labels: QA/Edit
