Repository OWASP/wstg, pull requests merged in 2019-09, with the labels that each got.

#166 Update 4.6.3_Testing_for_Privilege_Escalation_OTG-AUTHZ-003.md
  document/4_Web_Application_Security_Testing/4.6_Authorization_Testing/4.6.3_Testing_for_Privilege_Escalation_OTG-AUTHZ-003.md
Labels: QA/Edit

#151 4.8.5 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.5_Testing_for_SQL_Injection_OTG-INPVAL-005.md
Labels: Migration

#165 Update section, add expanded content (close #164)
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.1_Conduct_Search_Engine_Discovery_Reconnaissance_for_Information_Leakage_OTG-INFO-001.md
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/images/Google_cache_Operator_Search_Results_Example_20121219.jpg
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/images/Google_cache_Operator_Search_Results_Example_20190828.png
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/images/Google_site_Operator_Search_Results_Example_20121219.jpg
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/images/Google_site_Operator_Search_Results_Example_20190828.png
Labels: QA/Edit

#124 4.3 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.3_Configuration_and_Deployment_Management_Testing/4.3.10_Test_for_Subdomain_Takeover_OTG-CONFIG-010.md
  document/4_Web_Application_Security_Testing/4.3_Configuration_and_Deployment_Management_Testing/4.3.1_Test_Network_Infrastructure_Configuration_OTG-CONFIG-001.md
  document/4_Web_Application_Security_Testing/4.3_Configuration_and_Deployment_Management_Testing/4.3.2_Test_Application_Platform_Configuration_OTG-CONFIG-002.md
  document/4_Web_Application_Security_Testing/4.3_Configuration_and_Deployment_Management_Testing/4.3.3_Test_File_Extensions_Handling_for_Sensitive_Information_OTG-CONFIG-003.md
  document/4_Web_Application_Security_Testing/4.3_Configuration_and_Deployment_Management_Testing/4.3.4_Review_Old_Backup_and_Unreferenced_Files_for_Sensitive_Information_OTG-CONFIG-004.md
  document/4_Web_Application_Security_Testing/4.3_Configuration_and_Deployment_Management_Testing/4.3.5_Enumerate_Infrastructure_and_Application_Admin_Interfaces_OTG-CONFIG-005.md
  document/4_Web_Application_Security_Testing/4.3_Configuration_and_Deployment_Management_Testing/4.3.6_Test_HTTP_Methods_OTG-CONFIG-006.md
  document/4_Web_Application_Security_Testing/4.3_Configuration_and_Deployment_Management_Testing/4.3.7_Test_HTTP_Strict_Transport_Security_OTG-CONFIG-007.md
  document/4_Web_Application_Security_Testing/4.3_Configuration_and_Deployment_Management_Testing/4.3.8_Test_RIA_Cross_Domain_Policy_OTG-CONFIG-008.md
  document/4_Web_Application_Security_Testing/4.3_Configuration_and_Deployment_Management_Testing/4.3.9_Test_File_Permission_OTG-CONFIG-009.md
  document/4_Web_Application_Security_Testing/4.3_Configuration_and_Deployment_Management_Testing/4.3_Testing_for_Configuration_Management.md
Labels: Migration

#147 4.9.2 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.9_Testing_for_Error_Handling/4.9.2_Testing_for_Stack_Traces_OTG-ERR-002.md
Labels: Migration

#155 4.8.5.1 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.5.1_Testing_for_Oracle.md
Labels: Migration

#170 Update 4.2.2 Fingerprint Web Server (close #169)
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.2_Fingerprint_Web_Server_OTG-INFO-002.md
Labels: QA/Edit

#168 Fix Section 2: Inline links (close #167)
  document/2_Introduction/2_Introduction.md
Labels: Migration

#173 4.8.5.4 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.5.4_OWASP_Backend_Security_Project_Testing_PostgreSQL.md
Labels: QA/Edit

#176 Fix broken links
  document/4_Web_Application_Security_Testing/4_Web_Application_Penetration_Testing.md
Labels: Migration, QA/Edit

#157 4.8.5.3 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.5.3_Testing_for_SQL_Server.md
Labels: Migration

#156 4.8.5.2 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.5.2_Testing_for_MySQL.md
Labels: Migration

#177 README - Titlecaps Tweak
  README.md
Labels: QA/Edit

#123 Update 4.12.10_Testing_WebSockets_OTG-CLIENT-010.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.10_Testing_WebSockets_OTG-CLIENT-010.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12_Client_Side_Testing.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/images/OWASP_ZAP_WebSockets.png
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/images/WebSocket_Client.png
Labels: Migration

#174 4.8.5.5 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.5.5_Testing_for_MS_Access.md
Labels: Migration
