Repository OWASP/wstg, pull requests merged in 2019-04, with the labels that each got.

#36 Read Me Updates
  README.md
Labels: New

#34 Section 2 wikilinks etc
  document/2 Introduction/2 Introduction.md
  document/2 Introduction/images/640px-UseAndMisuseCase.jpg
  document/2 Introduction/images/ProportionSDLC.png
  document/2 Introduction/images/ProportionTest.png
  document/2 Introduction/images/SDLC.jpg
  document/2 Introduction/images/WindowExposure.jpg
Labels: Migration

#37 Section 3 Migration Tweaks
  document/3 The OWASP Testing Framework/3 The OWASP Testing Framework.md
  document/3 The OWASP Testing Framework/3.8 Penetration testing methodologies.md
  document/3 The OWASP Testing Framework/images/Typical_SDLC_Testing_Workflow.gif
Labels: Migration

#38 Section 2 Tweaks
  document/2 Introduction/2 Introduction.md
Labels: Migration, QA/Edit

#42 Add Google Group Link
  README.md
Labels: New

#41 Section 4 Migration Adjustments
  document/4 Web Application Security Testing/4 Web Application Penetration Testing.md
  document/4 Web Application Security Testing/4.1 Introduction and Objectives/4.1 Testing Introduction and objectives.md
  document/4 Web Application Security Testing/4.2 Information Gathering/4.2 Testing Information Gathering.md
  document/4 Web Application Security Testing/4.2 Information Gathering/4.2.1 Conduct search engine discovery reconnaissance for information leakage (OTG-INFO-001).markdown
  document/4 Web Application Security Testing/4.2 Information Gathering/4.2.1 Conduct search engine discovery reconnaissance for information leakage (OTG-INFO-001).md
  document/4 Web Application Security Testing/4.2 Information Gathering/4.2.2 Fingerprint Web Server (OTG-INFO-002).md
  document/4 Web Application Security Testing/4.2 Information Gathering/4.2.3 Review Webserver Metafiles for Information Leakage (OTG-INFO-003).md
  document/4 Web Application Security Testing/images/Google_cache_Operator_Search_Results_Example_20121219.jpg
  document/4 Web Application Security Testing/images/Google_site_Operator_Search_Results_Example_20121219.jpg
  document/4 Web Application Security Testing/images/Httprint.jpg
  document/4 Web Application Security Testing/images/Meta_Tag_Example-Facebook-Aug_2013.png
  document/4 Web Application Security Testing/images/Netcraft2.png
Labels: Migration

#45 Adding "Brute Forcing Weak Secrets used for JWT"
  Testing for APIs.md
Labels: New

#50 Add Badges to README
  README.md
Labels: enhancement

#46 Section 1.2 Tweaks
  document/1 Frontispiece/1.2 About The Open Web Application Security Project.md
Labels: Migration, QA/Edit

#52 README Trim
  OWASP Summit Outcome
  OWASP_Summit_Outcomes.md
  README.md
Labels: QA/Edit
