Repository OWASP/wstg, pull requests merged in 2019-08, with the labels that each got.

#135 4.7.6 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.6_Testing_for_Logout_Functionality_OTG-SESS-006.md
Labels: Migration

#129 4.7.2 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.2_Testing_for_Cookies_Attributes_OTG-SESS-002.md
Labels: Migration

#143 4.8.3 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.3_Testing_for_HTTP_Verb_Tampering_OTG-INPVAL-003.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/images/OPTIONS_verb_tampering.png
Labels: Migration

#134 4.7.5 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.5_Testing_for_CSRF_OTG-SESS-005.md
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/images/Session_Riding_Firewall_Management.gif
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/images/Session_Riding_Firewall_Management_2.gif
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/images/Session_riding.GIF
Labels: Migration

#127 4.6 Authorization Testing - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.6_Authorization_Testing/4.6.1_Testing_Directory_Traversal_File_Include_OTG-AUTHZ-001.md
  document/4_Web_Application_Security_Testing/4.6_Authorization_Testing/4.6.2_Testing_for_Bypassing_Authorization_Schema_OTG-AUTHZ-002.md
  document/4_Web_Application_Security_Testing/4.6_Authorization_Testing/4.6.3_Testing_for_Privilege_Escalation_OTG-AUTHZ-003.md
  document/4_Web_Application_Security_Testing/4.6_Authorization_Testing/4.6.4_Testing_for_Insecure_Direct_Object_References_OTG-AUTHZ-004.md
  document/4_Web_Application_Security_Testing/4.6_Authorization_Testing/4.6_Testing_for_Authorization.md
Labels: Migration

#126 4.5 Authentication Testing - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.10_Testing_for_Weaker_Authentication_in_Alternative_Channel_OTG-AUTHN-010.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.1_Testing_for_Credentials_Transported_over_an_Encrypted_Channel_OTG-AUTHN-001.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.2_Testing_for_Default_Credentials_OTG-AUTHN-002.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.3_Testing_for_Weak_Lock_Out_Mechanism_OTG-AUTHN-003.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.4_Testing_for_Bypassing_Authentication_Schema_OTG-AUTHN-004.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.5_Testing_for_Vulnerable_Remember_Password_OTG-AUTHN-005.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.6_Testing_for_Browser_Cache_Weaknesses_OTG-AUTHN-006.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.7_Testing_for_Weak_Password_Policy_OTG-AUTHN-007.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.8_Testing_for_Weak_Security_Question_Answer_OTG-AUTHN-008.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.9_Testing_for_Weak_Password_Change_or_Reset_Functionalities_OTG-AUTHN-009.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5_Testing_for_Authentication.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/images/Basm-directreq.jpg
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/images/Basm-parammod.jpg
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/images/Basm-sessid.jpg
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/images/Basm-sessid2.jpg
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/images/Basm-sqlinj.jpg
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/images/Basm-sqlinj2.gif
Labels: Migration

#137 4.8.2 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.2_Testing_for_Stored_Cross_Site_Scripting_OTG-INPVAL-002.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/images/RubyBeef.png
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/images/Stored_input_example.jpg
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/images/Stored_xss_example.jpg
Labels: Migration

#128 4.7.1 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.1_Testing_for_Session_Management_Schema_OTG-SESS-001.md
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7_Testing_for_Session_Management.md
Labels: Migration

#148 4.9 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.9_Testing_for_Error_Handling/4.9_Testing_for_Error_Handling.md
Labels: Migration

#130 4.7.3 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.3_Testing_for_Session_Fixation_OTG-SESS-003.md
Labels: Migration

#145 4.8.4 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.4_Testing_for_HTTP_Parameter_Pollution_OTG-INPVAL-004.md
Labels: Migration

#136 4.8.1 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.1_Testing_for_Reflected_Cross_Site_Scripting_OTG-INPVAL-001.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8_Testing_for_Input_Validation.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/images/Alert.png
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/images/XSS_Example1.png
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/images/XSS_Example2.png
Labels: Migration

#133 4.7.8 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.8_Testing_for_Session_Puzzling_OTG-SESS-008.md
Labels: Migration

#120 4.2 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.10_Map_Application_Architecture_OTG-INFO-010.md
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.1_Conduct_Search_Engine_Discovery_Reconnaissance_for_Information_Leakage_OTG-INFO-001.md
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.2_Fingerprint_Web_Server_OTG-INFO-002.md
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.3_Review_Webserver_Metafiles_for_Information_Leakage_OTG-INFO-003.md
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.4_Enumerate_Applications_on_Webserver_OTG-INFO-004.md
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.5_Review_Webpage_Comments_and_Metadata_for_Information_Leakage_OTG-INFO-005.md
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.6_Identify_Application_Entry_Points_OTG-INFO-006.md
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.7_Map_Execution_Paths_Through_Application_OTG-INFO-007.md
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.8_Fingerprint_Web_Application_Framework_OTG-INFO-008.md
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.9_Fingerprint_Web_Application_OTG-INFO-009.md
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2_Testing_Information_Gathering.md
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/images/Banshee_bottom_page.png
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/images/Cakephp_cookie.png
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/images/Drupal_botcha_disclosure.png
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/images/OWASPZAPSP.png
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/images/Owasp-Info.jpg
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/images/Owasp-wappalyzer.png
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/images/Robots-info-disclosure.png
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/images/Whatweb-sample.png
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/images/Wordpress_dirbusting.png
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/images/Zk_html_source.png
Labels: Migration

#131 4.7.4 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.4_Testing_for_Exposed_Session_Variables_OTG-SESS-004.md
Labels: Migration

#125 4.4 Identity Management Testing - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.4_Identity_Management_Testing/4.4.1_Test_Role_Definitions_OTG-IDENT-001.md
  document/4_Web_Application_Security_Testing/4.4_Identity_Management_Testing/4.4.2_Test_User_Registration_Process_OTG-IDENT-002.md
  document/4_Web_Application_Security_Testing/4.4_Identity_Management_Testing/4.4.3_Test_Account_Provisioning_Process_OTG-IDENT-003.md
  document/4_Web_Application_Security_Testing/4.4_Identity_Management_Testing/4.4.4_Testing_for_Account_Enumeration_and_Guessable_User_Account_OTG-IDENT-004.md
  document/4_Web_Application_Security_Testing/4.4_Identity_Management_Testing/4.4.5_Testing_for_Weak_or_Unenforced_Username_Policy_OTG-IDENT-005.md
  document/4_Web_Application_Security_Testing/4.4_Identity_Management_Testing/4.4_Identity_Management_Testing.md
  document/4_Web_Application_Security_Testing/4.4_Identity_Management_Testing/images/AuthenticationFailed.png
  document/4_Web_Application_Security_Testing/4.4_Identity_Management_Testing/images/Google_registration_page.jpg
  document/4_Web_Application_Security_Testing/4.4_Identity_Management_Testing/images/NoConfFound.jpg
  document/4_Web_Application_Security_Testing/4.4_Identity_Management_Testing/images/Userisnotactive.png
  document/4_Web_Application_Security_Testing/4.4_Identity_Management_Testing/images/Wordpress_authandusers.png
  document/4_Web_Application_Security_Testing/4.4_Identity_Management_Testing/images/Wordpress_registration_page.jpg
  document/4_Web_Application_Security_Testing/4.4_Identity_Management_Testing/images/Wordpress_useradd.png
Labels: Migration

#144 New content: 4.8.19 - Server Side Template Injection
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.19_Testing_for_Server_Side_Template_Injection_OTG-INPVAL-019.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/images/SSTI_XVWA.jpeg
Labels: New

#150 Adding testing guide checklist
  document/OWASP-Testing_Checklist.xlsx
Labels: New

#154 Fix, update 0-3
  document/0_Foreword/0_Foreword.md
  document/1_Frontispiece/1.2_About_The_Open_Web_Application_Security_Project.md
  document/2_Introduction/2_Introduction.md
  document/2_Introduction/images/640px-UseAndMisuseCase.jpg
  document/3_The_OWASP_Testing_Framework/3_The_OWASP_Testing_Framework.md
Labels: QA/Edit

#163 Checklist Move & Intro
  checklist/OWASP-Testing_Checklist.xlsx
  checklist/README.md
Labels: Repo

#159 Add guideline for figure captions (close #158)
  README.md
Labels: Repo
