Repository OWASP/wstg, pull requests merged in 2019-10, with the labels that each got.

#179 OTG-4.8.6 - v4 migration cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.6_Testing_for_LDAP_Injection_OTG-INPVAL-006.md
Labels: Migration

#175 4.8.5.6 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.5.6_Testing_for_NoSQL_Injection.md
Labels: Migration

#178 Migrate 4.10 Testing for Weak Cryptography
  document/4_Web_Application_Security_Testing/4.10_Testing_for_Weak_Cryptography/4.10.1_Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection_OTG-CRYPST-001.md
  document/4_Web_Application_Security_Testing/4.10_Testing_for_Weak_Cryptography/4.10.2_Testing_for_Padding_Oracle_OTG-CRYPST-002.md
  document/4_Web_Application_Security_Testing/4.10_Testing_for_Weak_Cryptography/4.10.3_Testing_for_Sensitive_Information_Sent_via_Unencrypted_Channels_OTG-CRYPST-003.md
  document/4_Web_Application_Security_Testing/4.10_Testing_for_Weak_Cryptography/4.10.4_Testing_for_Weak_Encryption_OTG-CRYPST-004.md
  document/4_Web_Application_Security_Testing/4.10_Testing_for_Weak_Cryptography/4.10_Testing_for_Weak_Cryptography.md
Labels: Migration

#102 Template first revision
  README.md
  template/999.1_FooTest_Template_OTG-FOO-001.md
  template/999.2_Template_Explanation_OTG-FOO-002.md
  template/images/foocircle.png
Labels: Repo, enhancement

#146 4.9.1 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.9_Testing_for_Error_Handling/4.9.1_Testing_for_Error_Code_OTG-ERR-001.md
Labels: Migration, QA/Edit

#153 4.11 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.1_Test_Business_Logic_Data_Validation_OTG-BUSLOGIC-001.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.2_Test_Ability_to_Forge_Requests_OTG-BUSLOGIC-002.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.3_Test_Integrity_Checks_OTG-BUSLOGIC-003.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.4_Test_for_Process_Timing_OTG-BUSLOGIC-004.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.5_Test_Number_of_Times_a_Function_Can_Be_Used_Limits_OTG-BUSLOGIC-005.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.6_Testing_for_the_Circumvention_of_Work_Flows_OTG-BUSLOGIC-006.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.7_Test_Defenses_Against_Application_Mis-use_OTG-BUSLOGIC-007.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.8_Test_Upload_of_Unexpected_File_Types_OTG-BUSLOGIC-008.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.9_Test_Upload_of_Malicious_Files_OTG-BUSLOGIC-009.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11_Testing_for_Business_Logic.md
Labels: Migration, QA/Edit

#187 OTG-4.8.7 - v4 migration cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.7_Testing_for_ORM_Injection_OTG-INPVAL-007.md
Labels: Migration, QA/Edit

#189 OTG-4.8.9 - v4 migration cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.9_Testing_for_SSI_Injection_OTG-INPVAL-009.md
Labels: Migration, QA/Edit

#190 4.1 Clarify passive and active testing (close #161)
  document/4_Web_Application_Security_Testing/4.1_Introduction_and_Objectives/4.1_Testing_Introduction_and_Objectives.md
Labels: QA/Edit

#194 OTG-4.8.10 - v4 migration cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.10_Testing_for_XPath_Injection_OTG-INPVAL-010.md
Labels: Migration, QA/Edit

#196 OTG-4.8.12 - v4 migration cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.12_Testing_for_Code_Injection_OTG-INPVAL-012.md
Labels: Migration, QA/Edit

#197 OTG-4.8.12.1 - v4 migration cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.12.1_Testing_for_Local_File_Inclusion.md
Labels: Migration, QA/Edit

#198 OTG-4.8.12.2 - v4 migration cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.12.2_Testing_for_Remote_File_Inclusion.md
Labels: Migration, QA/Edit

#200 OTG-4.8.14 - v4 migration cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.14_Testing_for_Buffer_Overflow_OTG-INPVAL-014.md
Labels: Migration, QA/Edit

#201 OTG-4.8.14.1 - v4 migration cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.14.1_Testing_for_Heap_Overflow.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/images/Heap_overflow_vulnerability.gif
Labels: Migration, QA/Edit

#202 OTG-4.8.14.2 - v4 migration cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.14.2_Testing_for_Stack_Overflow.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/images/Stack_overflow_vulnerability.gif
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/images/Stack_overflow_vulnerability_2.gif
Labels: Migration, QA/Edit

#203 OTG-4.8.14.3 - v4 migration cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.14.3_Testing_for_Format_String.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/images/IDA_Pro.gif
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/images/IDA_Pro_2.gif
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/images/ITS4.gif
Labels: Migration, QA/Edit

#204 OTG-4.8.15 - v4 migration cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.15_Testing_for_Incubated_Vulnerability_OTG-INPVAL-015.md
Labels: Migration, QA/Edit

#205 OTG-4.8.16 - v4 migration cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.16_Testing_for_HTTP_Splitting_Smuggling_OTG-INPVAL-016.md
Labels: Migration, QA/Edit

#206 OTG-4.8.17 - v4 migration cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.17_Testing_for_HTTP_Incoming_Requests_OTG-INPVAL-017.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8_Testing_for_Input_Validation.md
  document/OWASP_Testing_Guide_v4_Table_of_Contents.md
Labels: Migration, QA/Edit

#207 OTG-4.8.18 - v4 migration cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.18_Testing_for_Host_Header_Injection_OTG-INPVAL-018.md
Labels: Migration, QA/Edit

#214 Fix Image names
  document/2_Introduction/2_Introduction.md
  document/3_The_OWASP_Testing_Framework/3_The_OWASP_Testing_Framework.md
  document/4_Web_Application_Security_Testing/4.10_Testing_for_Weak_Cryptography/4.10.1_Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection_OTG-CRYPST-001.md
  document/4_Web_Application_Security_Testing/4.3_Configuration_and_Deployment_Management_Testing/4.3.1_Test_Network_Infrastructure_Configuration_OTG-CONFIG-001.md
  document/4_Web_Application_Security_Testing/4.3_Configuration_and_Deployment_Management_Testing/4.3.3_Test_File_Extensions_Handling_for_Sensitive_Information_OTG-CONFIG-003.md
Labels: Migration, QA/Edit

#195 OTG-4.8.11 - v4 migration cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.11_Testing_for_IMAP_SMTP_Injection_OTG-INPVAL-011.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/images/Imap-smtp-injection.png
Labels: Migration, QA/Edit

#188 OTG-4.8.8 - v4 migration cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.8_Testing_for_XML_Injection_OTG-INPVAL-008.md
Labels: Migration, QA/Edit

#215 Fix indentation in code blocks - otg.4.9
  document/4_Web_Application_Security_Testing/4.9_Testing_for_Error_Handling/4.9.1_Testing_for_Error_Code_OTG-ERR-001.md
  document/4_Web_Application_Security_Testing/4.9_Testing_for_Error_Handling/4.9.2_Testing_for_Stack_Traces_OTG-ERR-002.md
Labels: Migration, QA/Edit

#208 Updating links and linting issues in Appendix B, C, D
  document/Appx.B_Suggested_Reading/Appx.B_Suggested_Reading.md
  document/Appx.C_Fuzz_Vectors/Appx.C_Fuzz_Vectors.md
  document/Appx.D_Encoded_Injection/Appx.D_Encoded_Injection.md
Labels: QA/Edit

#191 Add length and common passwords to the password policy guidance
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.7_Testing_for_Weak_Password_Policy_OTG-AUTHN-007.md
Labels: QA/Edit

#199 OTG-4.8.13 - v4 migration cleanup
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.13_Testing_for_Command_Injection_OTG-INPVAL-013.md
Labels: Migration, QA/Edit

#193 Fix broken image link and markdown
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.13_Testing_for_Cross_Site_Script_Inclusion_OTG-CLIENT-013.md
Labels: Migration, QA/Edit

#217 Fix linting in WIP extra files
  OWASP_Summit_Outcomes.md
  Testing_for_APIs.md
  Testing_for_Horizontal_Bypassing_Authorization_Schema_OTG-AUTHZ-002.md
  Testing_for_Server-Side_Request_Forgery.md
  Testing_for_Vertical_Bypassing_Authorization_Schema_OTG-AUTHZ-00X.md
  document/2_Introduction/2_Introduction.md
Labels: Migration, QA/Edit

#218 Fix linting in Appx.D_Encoded_Injection
  document/Appx.D_Encoded_Injection/Appx.D_Encoded_Injection.md
Labels: Migration, QA/Edit

#184 Migration clean up and fixes for 4.12 (close #88)
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.10_Testing_WebSockets_OTG-CLIENT-010.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.11_Test_Web_Messaging_OTG-CLIENT-011.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.11_Testing_Web_Messaging_OTG-CLIENT-011.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.12_Test_Local_Storage_OTG-CLIENT-012.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.12_Testing_Web_Storage_OTG-CLIENT-012.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.13_Testing_for_Cross_Site_Script_Inclusion_OTG-CLIENT-013.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.1_Testing_for_DOM-based_Cross_Site_Scripting_OTG-CLIENT-001.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.2_Testing_for_JavaScript_Execution_OTG-CLIENT-002.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.3_Testing_for_HTML_Injection_OTG-CLIENT-003.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.4_Testing_for_Client_Side_URL_Redirect_OTG-CLIENT-004.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.5_Testing_for_CSS_Injection_OTG-CLIENT-005.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.6_Testing_for_Client_Side_Resource_Manipulation_OTG-CLIENT-006.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.7_Test_Cross_Origin_Resource_Sharing_OTG-CLIENT-007.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.7_Testing_Cross_Origin_Resource_Sharing_OTG-CLIENT-007.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.8_Testing_for_Cross_Site_Flashing_OTG-CLIENT-008.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.9_Testing_for_Clickjacking_OTG-CLIENT-009.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12_Client_Side_Testing.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/images/800px-Clickjacking_description.png
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/images/800px-Masked_iframe.png
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/images/Storage-xss.png
Labels: HacktoberFest, Migration, QA/Edit

#181 OTG-152 remove Webscarab references
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11_Testing_for_Business_Logic.md
  document/4_Web_Application_Security_Testing/4.4_Identity_Management_Testing/4.4.4_Testing_for_Account_Enumeration_and_Guessable_User_Account_OTG-IDENT-004.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.1_Testing_for_Credentials_Transported_over_an_Encrypted_Channel_OTG-AUTHN-001.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.4_Testing_for_Bypassing_Authentication_Schema_OTG-AUTHN-004.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.6_Testing_for_Browser_Cache_Weaknesses_OTG-AUTHN-006.md
  document/4_Web_Application_Security_Testing/4.6_Authorization_Testing/4.6.1_Testing_Directory_Traversal_File_Include_OTG-AUTHZ-001.md
  document/4_Web_Application_Security_Testing/4.6_Authorization_Testing/4.6.2_Testing_for_Bypassing_Authorization_Schema_OTG-AUTHZ-002.md
  document/4_Web_Application_Security_Testing/4.6_Authorization_Testing/4.6.3_Testing_for_Privilege_Escalation_OTG-AUTHZ-003.md
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.3_Testing_for_Session_Fixation_OTG-SESS-003.md
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.5_Testing_for_CSRF_OTG-SESS-005.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.1_Testing_for_Reflected_Cross_Site_Scripting_OTG-INPVAL-001.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.2_Testing_for_Stored_Cross_Site_Scripting_OTG-INPVAL-002.md
  document/Appx.A_Testing_Tools_Resource/Appx.A_Testing_Tools.md
Labels: HacktoberFest, QA/Edit

#219 Fix linting errors - markdownlint check
  checklist/README.md
  document/1_Frontispiece/1.2_About_The_Open_Web_Application_Security_Project.md
  document/4_Web_Application_Security_Testing/4.10_Testing_for_Weak_Cryptography/4.10.1_Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection_OTG-CRYPST-001.md
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.3_Review_Webserver_Metafiles_for_Information_Leakage_OTG-INFO-003.md
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.9_Fingerprint_Web_Application_OTG-INFO-009.md
  document/4_Web_Application_Security_Testing/4.3_Configuration_and_Deployment_Management_Testing/4.3.10_Test_for_Subdomain_Takeover_OTG-CONFIG-010.md
  document/4_Web_Application_Security_Testing/4.3_Configuration_and_Deployment_Management_Testing/4.3.4_Review_Old_Backup_and_Unreferenced_Files_for_Sensitive_Information_OTG-CONFIG-004.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.7_Testing_for_Weak_Password_Policy_OTG-AUTHN-007.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.17_Testing_for_HTTP_Incoming_Requests_OTG-INPVAL-017.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.1_Testing_for_Reflected_Cross_Site_Scripting_OTG-INPVAL-001.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.5.4_OWASP_Backend_Security_Project_Testing_PostgreSQL.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.6_Testing_for_LDAP_Injection_OTG-INPVAL-006.md
  document/4_Web_Application_Security_Testing/4_Web_Application_Penetration_Testing.md
  template/999.1_FooTest_Template_OTG-FOO-001.md
  template/999.2_Template_Explanation_OTG-FOO-002.md
Labels: Repo

#216 Fix: Update template to include remediation section
  template/999.1_FooTest_Template_OTG-FOO-001.md
  template/999.2_Template_Explanation_OTG-FOO-002.md
Labels: QA/Edit, Repo

#220 Fix linting issues in 4.12
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.10_Testing_WebSockets_OTG-CLIENT-010.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.11_Testing_Web_Messaging_OTG-CLIENT-011.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.1_Testing_for_DOM-based_Cross_Site_Scripting_OTG-CLIENT-001.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.4_Testing_for_Client_Side_URL_Redirect_OTG-CLIENT-004.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.8_Testing_for_Cross_Site_Flashing_OTG-CLIENT-008.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.9_Testing_for_Clickjacking_OTG-CLIENT-009.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/images/Clickjacking_description.png
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/images/Clickjacking_example_malicious_page_1.png
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/images/Clickjacking_example_malicious_page_2.png
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/images/Clickjacking_example_malicious_page_3.png
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/images/Clickjacking_example_step2.png
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/images/Masked_iframe.png
Labels: Migration, QA/Edit

#222 Implement CI checks and linter
  .markdownlint.json
  .travis.yml
  package.json
Labels: Repo

#226 Create CoC File
  CODE_OF_CONDUCT.md
Labels: Repo
