Repository OWASP/wstg, pull requests merged in 2019-07, with the labels that each got.

#101 OTG-73 Create a Contributing Guide
  CONTRIBUTING.md
Labels: Repo

#104 Fixes #78 Minimal change to prevent Windows Defender detection
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.9_Test_Upload_of_Malicious_Files_OTG-BUSLOGIC-009.md
Labels: bug

#105 Appx.E Misc - v4 Migration Cleanup - fixes #94
  document/Appx.E_Misc/AppxE_History.md
Labels: Migration

#103 Table of Contents - v4 Migration Cleanup - closes #95
  document/0_Foreword/0_Foreword.md
  document/OWASP_Testing_Guide_v4_Table_of_Contents.md
Labels: Migration

#106 Appx.D Encoded Injection - v4 Migration Cleanup - Fixes #93
  document/Appx.D_Encoded_Injection/Appx.D_Encoded_Injection.md
Labels: Migration

#108 Appx.C Fuzz Vectors - v4 Migration Cleanup
  document/Appx.C_Fuzz_Vectors/Appx.C_Fuzz_Vectors.md
Labels: Migration

#107 Appx.B Suggested Reading - v4 Migration Cleanup - Fixes #91
  document/Appx.B_Suggested_Reading/Appx.B_Suggested_Reading.md
Labels: Migration

#109 Implement gitignore
  .gitignore
Labels: Repo

#113 0 Foreword - v4 Migration Cleanup
  document/0_Foreword/0_Foreword.md
Labels: Migration

#114 1 Frontispiece - v4 Migration Cleanup
  document/1_Frontispiece/1.2_About_The_Open_Web_Application_Security_Project.md
  document/1_Frontispiece/1_Frontispiece.md
  document/1_Frontispiece/images/Owasp_logo_icon.jpg
  document/1_Frontispiece/images/follow_badge.png
Labels: Migration

#115 2 Introduction - v4 Migration Cleanup
  document/2_Introduction/2_Introduction.md
Labels: Migration

#117 3 The OWASP Testing Framework - v4 Migration Cleanup
  document/3_The_OWASP_Testing_Framework/3.8_Penetration_Testing_Methodologies.md
  document/3_The_OWASP_Testing_Framework/3_The_OWASP_Testing_Framework.md
Labels: Migration, QA/Edit

#116 Add help to run lint checker in local environment
  CONTRIBUTING.md
Labels: Repo

#111 5 Reporting - v4 Migration Cleanup - Closes #89
  document/5_Reporting/Reporting.md
Labels: Migration

#118 Update README to Push Contributors Forward
  README.md
Labels: Repo

#119 4.1 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.1_Introduction_and_Objectives/4.1.1_Testing_Checklist.md
  document/4_Web_Application_Security_Testing/4.1_Introduction_and_Objectives/4.1_Testing_Introduction_and_Objectives.md
Labels: Migration

#132 4.7.7 - v4 Migration Cleanup
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.7_Test_Session_Timeout_OTG-SESS-007.md
Labels: Migration

#110 Appx.A Testing Tools Resource - v4 Migration Cleanup
  document/Appx.A_Testing_Tools_Resource/Appx.A_Testing_Tools.md
Labels: Migration
