Repository OWASP/wstg, pull requests merged in 2020-07, with the labels that each got.

#521 Add other headers for Authz Bypass
  document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
Labels: revise

#524 Update Active Testing list to match chapters
  document/4-Web_Application_Security_Testing/00-Introduction_and_Objectives/README.md
Labels: revise

#525 Link to the main OWASP Cheat Sheet website, not GitHub
  document/4-Web_Application_Security_Testing/11-Client_Side_Testing/01-Testing_for_DOM-based_Cross_Site_Scripting.md
  document/4-Web_Application_Security_Testing/11-Client_Side_Testing/05-Testing_for_CSS_Injection.md
  template/999-Foo_Testing/2-Template_Explanation.md
Labels: revise

#527 Remove un-necessary file
  OWASP_Summit_Outcomes.md
Labels: repo

#526 textlint: Handle "client-" and "server-" side terms
  .textlintrc
  document/4-Web_Application_Security_Testing/00-Introduction_and_Objectives/README.md
  document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/03-Test_File_Extensions_Handling_for_Sensitive_Information.md
  document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/04-Review_Old_Backup_and_Unreferenced_Files_for_Sensitive_Information.md
  document/4-Web_Application_Security_Testing/04-Authentication_Testing/05-Testing_for_Vulnerable_Remember_Password.md
  document/4-Web_Application_Security_Testing/06-Session_Management_Testing/01-Testing_for_Session_Management_Schema.md
  document/4-Web_Application_Security_Testing/06-Session_Management_Testing/02-Testing_for_Cookies_Attributes.md
  document/4-Web_Application_Security_Testing/06-Session_Management_Testing/04-Testing_for_Exposed_Session_Variables.md
  document/4-Web_Application_Security_Testing/06-Session_Management_Testing/05-Testing_for_Cross_Site_Request_Forgery.md
  document/4-Web_Application_Security_Testing/06-Session_Management_Testing/07-Testing_Session_Timeout.md
  document/4-Web_Application_Security_Testing/06-Session_Management_Testing/08-Testing_for_Session_Puzzling.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/04-Testing_for_HTTP_Parameter_Pollution.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05-Testing_for_SQL_Injection.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05.8-Testing_for_Client-side.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/06-Testing_for_LDAP_Injection.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/11.1-Testing_for_Local_File_Inclusion.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/14-Testing_for_Incubated_Vulnerability.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/16-Testing_for_HTTP_Incoming_Requests.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/18-Testing_for_Server-side_Template_Injection.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/README.md
  document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/02-Testing_for_Padding_Oracle.md
  document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/01-Test_Business_Logic_Data_Validation.md
  document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/03-Test_Integrity_Checks.md
  document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/08-Test_Upload_of_Unexpected_File_Types.md
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/01-Testing_for_DOM-based_Cross_Site_Scripting.md
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/02-Testing_for_JavaScript_Execution.md
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/03-Testing_for_HTML_Injection.md
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/04-Testing_for_Client-side_URL_Redirect.md
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/05-Testing_for_CSS_Injection.md
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/06-Testing_for_Client-side_Resource_Manipulation.md
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/07-Testing_Cross_Origin_Resource_Sharing.md
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/08-Testing_for_Cross_Site_Flashing.md
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/09-Testing_for_Clickjacking.md
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/10-Testing_WebSockets.md
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/11-Testing_Web_Messaging.md
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/12-Testing_Browser_Storage.md
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/13-Testing_for_Cross_Site_Script_Inclusion.md
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/README.md
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/images/Clickjacking_description.png
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/images/Clickjacking_example_malicious_page_1.png
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/images/Clickjacking_example_malicious_page_2.png
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/images/Clickjacking_example_malicious_page_3.png
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/images/Clickjacking_example_step2.png
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/images/Masked_iframe.png
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/images/OWASP_ZAP_WebSockets.png
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/images/Storage-xss.png
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/images/WebSocket_Client.png
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/images/XSSI1.jpeg
  document/4-Web_Application_Security_Testing/README.md
  document/5-Reporting/README.md
  document/README.md
Labels: repo

#528 Facilitate Manual PDF Builds
  .github/workflows/build-pdf.yml
Labels: enhancement, repo
