Repository OWASP/wstg, pull requests merged in 2020-10, with the labels that each got.

#555 Rewrite of TLS testing guide
  checklist/Testing_Checklist.md
  document/4-Web_Application_Security_Testing/04-Authentication_Testing/01-Testing_for_Credentials_Transported_over_an_Encrypted_Channel.md
  document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
  document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_Transport_Layer_Security.md
  document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/03-Testing_for_Sensitive_Information_Sent_via_Unencrypted_Channels.md
  document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/README.md
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/10-Testing_WebSockets.md
  document/5-Reporting/README.md
  document/README.md
Labels: revise

#576 Preserve line breaks in linting comments
  .github/workflows/md-lint-check.yml
  .github/workflows/md-textlint-check.yml
Labels: repo

#579 Fix 578: Linter can now handle triple backticks and comment
  .github/workflows/md-lint-check.yml
Labels: repo

#582 workflows: Address set-env deprecation
  .github/workflows/www_latest_update.yml
  .github/workflows/www_stable_update.yml
Labels: repo

#586 Markdown Checklist - Terminology Tweaks
  checklist/Testing_Checklist.md
Labels: revise

#585 Issue 556 - Linkify Appendix C
  document/6-Appendix/C-Fuzz_Vectors.md
Labels: revise

#584 Feature json checklist 376
  .github/workflows/build-json.yml
  json/scripts/make-json.sh
  package.json
Labels: enhancement, repo

#600 Move workflow configs and scripts out of root
  .github/configs/.markdownlint.json
  .github/configs/.textlintrc
  .github/configs/markdown-link-check-config.json
  .github/pdf/README.md
  .github/pdf/assets/back-cover.png
  .github/pdf/assets/cover-v4.1.jpg
  .github/pdf/assets/cover.jpg
  .github/pdf/assets/pdf-style.css
  .github/pdf/assets/second-cover.png
  .github/pdf/pdf-config.json
  .github/pdf/scripts/make-pdf.sh
  .github/scripts/make-json.sh
  .github/workflows/README.md
  .github/workflows/md-link-check.yml
  .github/workflows/md-lint-check.yml
  .github/workflows/md-textlint-check.yml
  .github/workflows/www_latest_update.yml
  .github/workflows/www_stable_update.yml
  .github/www/README.md
  .github/www/assets/202006-owasp_material/Github/Github - Shield 400x400 - Gradient – 1.png
  .github/www/assets/202006-owasp_material/Twitter/Twitter - Shield 400x400.png
  .github/www/assets/202006-owasp_material/Twitter/Twitter Cover - 1500 x 500.png
  .github/www/assets/README.md
  .github/www/latest/README.md
  .github/www/latest/info.md
  .github/www/latest/prepend.nav
  .github/www/latest/prepend.txt
  .github/www/stable/README.md
  .github/www/stable/info.md
  .github/www/stable/prepend.nav
  .github/www/stable/prepend.txt
  .github/www/v41/README.md
  .github/www/v41/info.md
  .github/www/v41/prepend.nav
  .github/www/v41/prepend.txt
  package.json
Labels: repo
