Repository OWASP/wstg, pull requests merged in 2020-06, with the labels that each got.

#491 Terminology Consistency & Various Tweaks
  document/4-Web_Application_Security_Testing/01-Information_Gathering/02-Fingerprint_Web_Server.md
  document/4-Web_Application_Security_Testing/04-Authentication_Testing/02-Testing_for_Default_Credentials.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/01-Testing_for_Reflected_Cross_Site_Scripting.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05-Testing_for_SQL_Injection.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05.1-Testing_for_Oracle.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05.3-Testing_for_SQL_Server.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/13.1-Testing_for_Heap_Overflow.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/13.2-Testing_for_Stack_Overflow.md
  document/6-Appendix/A-Testing_Tools_Resource.md
Labels: revise

#496 textlint part 2
  .textlintrc
Labels: enhancement, repo

#500 Store graphics/assets, and update credits to include Ramzi Fazah
  document/1-Frontispiece/README.md
  markdown-link-check-config.json
  www/README.md
  www/assets/202006-owasp_material/Github/Github - Shield 400x400 - Gradient – 1.png
  www/assets/202006-owasp_material/Twitter/Twitter - Shield 400x400.png
  www/assets/202006-owasp_material/Twitter/Twitter Cover - 1500 x 500.png
  www/assets/README.md
Labels: repo

#504 Add GitHub Actions README.md
  .github/workflows/README.md
  .github/workflows/md-textlint-check.yml
Labels: enhancement, repo

#508 Fix grammar in Test HTTP Strict Transport Security #507
  document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/07-Test_HTTP_Strict_Transport_Security.md
Labels: revise

#506 Update 1-Penetration_Testing_Methodologies.md
  document/3-The_OWASP_Testing_Framework/1-Penetration_Testing_Methodologies.md
Labels: revise

#511 Update refresh-stale.yml
  .github/workflows/refresh-stale.yml
Labels: repo

#512 Address OWASP Trademark Registration
  README.md
  document/0-Foreword/README.md
  document/1-Frontispiece/README.md
Labels: revise

#513 Adjust refresh-stale to run once a month
  .github/workflows/refresh-stale.yml
Labels: repo

#514 Confusion between admin and index endpoint
  document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
Labels: revise

#516 Added Fortify WebInspect/SCA as commercials black-box and source code…
  document/6-Appendix/A-Testing_Tools_Resource.md
Labels: revise

#519 Add SSTI Reference
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/18-Testing_for_Server_Side_Template_Injection.md
Labels: revise
