Repository OWASP/wstg, pull requests merged in 2020-04, with the labels that each got.

#405 Add "Latest" Deploy Job and Supporting Material
  .github/workflows/md-lint-check.yml
  .github/workflows/www_latest_update.yml
  www/README.md
  www/latest/README.md
  www/latest/info.md
  www/latest/prepend.nav
  www/latest/prepend.txt
Labels: repo

#409 Added new image for SDLC in Introduction
  document/2-Introduction/images/ProportionSDLC.png
  document/2-Introduction/images/ProportionTest.png
  document/2-Introduction/images/SDLC.jpg
  document/3-The_OWASP_Testing_Framework/images/Typical_SDLC_Testing_Workflow.gif
  document/4-Web_Application_Security_Testing/01-Information_Gathering/01-Conduct_Search_Engine_Discovery_Reconnaissance_for_Information_Leakage.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/images/Google_cache_Operator_Search_Results_Example_20190828.png
  document/4-Web_Application_Security_Testing/01-Information_Gathering/images/Google_cache_Operator_Search_Results_Example_20200406.png
  document/4-Web_Application_Security_Testing/01-Information_Gathering/images/Google_site_Operator_Search_Results_Example_20190828.png
  document/4-Web_Application_Security_Testing/01-Information_Gathering/images/Google_site_Operator_Search_Results_Example_20200406.png
  document/4-Web_Application_Security_Testing/01-Information_Gathering/images/Owasp-wappalyzer.png
  document/4-Web_Application_Security_Testing/06-Session_Management_Testing/images/Session_riding.GIF
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/images/Alert.png
  document/4-Web_Application_Security_Testing/11-Client_Side_Testing/images/Clickjacking_description.png
Labels: revise

#412 Correct path during var setup
  .github/workflows/www_latest_update.yml
Labels: repo

#413 Switch to checkout v2 and totally ignore `www` dir
  .github/workflows/md-link-check.yml
  .github/workflows/md-lint-check.yml
  .github/workflows/www_latest_update.yml
  package.json
Labels: repo

#415 Remove header blocks in 4.7 README
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/README.md
Labels: revise

#414 Fix set-env syntax
  .github/workflows/www_latest_update.yml
Labels: repo

#418 Create README for Section 3
  document/3-The_OWASP_Testing_Framework/README.md
  document/README.md
Labels: revise

#421 Fix typo, missed env var, and revise nav generation
  .github/workflows/www_latest_update.yml
Labels: repo

#422 Tweak Forward and Section 3 README Anchors
  document/1-Frontispiece/README.md
  document/3-The_OWASP_Testing_Framework/0-The_OWASP_Testing_Framework.md
  document/3-The_OWASP_Testing_Framework/README.md
  document/README.md
Labels: revise

#427 Appendix Re-org
  .github/workflows/www_latest_update.yml
  document/4-Web_Application_Security_Testing/00-Introduction_and_Objectives/README.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05.3-Testing_for_SQL_Server.md
  document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/00-Introduction_to_Business_Logic.md
  document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/README.md
  document/4-Web_Application_Security_Testing/README.md
  document/6-Appendix/A-Testing_Tools_Resource.md
  document/6-Appendix/B-Suggested_Reading.md
  document/6-Appendix/C-Fuzz_Vectors.md
  document/6-Appendix/D-Encoded_Injection.md
  document/6-Appendix/E-History.md
  document/6-Appendix/README.md
  document/README.md
Labels: revise

#235 Implement PDF build
  .github/workflows/build-pdf.yml
  .gitignore
  package.json
  pdf/assets/back-cover.png
  pdf/assets/cover.jpg
  pdf/assets/pdf-style.css
  pdf/assets/second-cover.png
  pdf/pdf-config.json
  pdf/scripts/make-pdf.sh
Labels: repo

#430 Add README to pdf directory
  pdf/README.md
Labels: repo

#431 Fix: Typos and Acronym Caps
  document/3-The_OWASP_Testing_Framework/1-Penetration_Testing_Methodologies.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/04-Enumerate_Applications_on_Webserver.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/08-Fingerprint_Web_Application_Framework.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/09-Fingerprint_Web_Application.md
  document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/02-Test_Application_Platform_Configuration.md
  document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/07-Test_HTTP_Strict_Transport_Security.md
  document/4-Web_Application_Security_Testing/04-Authentication_Testing/02-Testing_for_Default_Credentials.md
  document/4-Web_Application_Security_Testing/04-Authentication_Testing/03-Testing_for_Weak_Lock_Out_Mechanism.md
  document/4-Web_Application_Security_Testing/04-Authentication_Testing/10-Testing_for_Weaker_Authentication_in_Alternative_Channel.md
  document/4-Web_Application_Security_Testing/06-Session_Management_Testing/01-Testing_for_Session_Management_Schema.md
  document/4-Web_Application_Security_Testing/06-Session_Management_Testing/05-Testing_for_Cross_Site_Request_Forgery.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/01-Testing_for_Reflected_Cross_Site_Scripting.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/02-Testing_for_Stored_Cross_Site_Scripting.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/03-Testing_for_HTTP_Verb_Tampering.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/04-Testing_for_HTTP_Parameter_Pollution.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/12-Testing_for_Command_Injection.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/16-Testing_for_HTTP_Incoming_Requests.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/17-Testing_for_Host_Header_Injection.md
  document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
  document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/01-Test_Business_Logic_Data_Validation.md
  document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/02-Test_Ability_to_Forge_Requests.md
  document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/03-Test_Integrity_Checks.md
  document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/04-Test_for_Process_Timing.md
  document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/07-Test_Defenses_Against_Application_Misuse.md
  document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/08-Test_Upload_of_Unexpected_File_Types.md
  document/4-Web_Application_Security_Testing/11-Client_Side_Testing/03-Testing_for_HTML_Injection.md
  document/4-Web_Application_Security_Testing/11-Client_Side_Testing/08-Testing_for_Cross_Site_Flashing.md
  document/4-Web_Application_Security_Testing/11-Client_Side_Testing/09-Testing_for_Clickjacking.md
  document/4-Web_Application_Security_Testing/11-Client_Side_Testing/13-Testing_for_Cross_Site_Script_Inclusion.md
  document/6-Appendix/D-Encoded_Injection.md
Labels: revise

#429 Remove number sign from anchor link names 4.1.8
  document/4-Web_Application_Security_Testing/01-Information_Gathering/08-Fingerprint_Web_Application_Framework.md
Labels: revise

#428 Fix link fragment parsing issue in PDF build
  pdf/scripts/make-pdf.sh
Labels: repo

#434 Workround for duplicate fragment links issue in v4.1 PDF build
  pdf/scripts/make-pdf.sh
Labels: repo

#432 Add Hugo Costa to the credits
  document/1-Frontispiece/README.md
Labels: revise

#433 Checklist README tweaks for v4.1
  checklist/README.md
  checklist/WSTG-Checklist_v4.0.xlsx
Labels: revise

#425 Add Stable and Versioned Publishing Job
  .github/workflows/www_stable_update.yml
  www/stable/README.md
  www/stable/info.md
  www/stable/prepend.nav
  www/stable/prepend.txt
  www/v41/README.md
  www/v41/info.md
  www/v41/prepend.nav
  www/v41/prepend.txt
Labels: repo

#436 Fix top TOC links, Make same as the section titles
  document/README.md
Labels: revise

#435 Add v4.1 version specific cover image for PDF
  pdf/assets/cover-v4.1.jpg
  pdf/scripts/make-pdf.sh
Labels: repo

#439 Fix issue in page 189, fragment link parsing
  pdf/scripts/make-pdf.sh
Labels: repo

#440 Change content to align left inside the code blocks in PDF
  pdf/assets/pdf-style.css
Labels: repo

#441 Add .gitattributes and consistently use LF for all text files
  .gitattributes
  Testing_for_Horizontal_Bypassing_Authorization_Schema_WSTG-AUTHZ-002.md
  Testing_for_Vertical_Bypassing_Authorization_Schema_WSTG-AUTHZ-00X.md
  www/latest/prepend.txt
  www/stable/prepend.txt
  www/v41/prepend.txt
Labels: Blocked, repo

#442 Update contribution guide
  CONTRIBUTING.md
Labels: repo

#443 v4 Credits conform to PDF
  document/6-Appendix/E-History.md
Labels: revise

#445 Maintain indent in _config.yml when processing
  .github/workflows/www_stable_update.yml
Labels: repo

#447 Added Testing for HTTP Method Overriding
  document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
Labels: new

#453 Section 2 content review and edits
  document/2-Introduction/README.md
Labels: revise
