Repository OWASP/wstg, pull requests merged in 2020-05, with the labels that each got.

#452 Change WSTG-INFO-05 to Add Review Frontend for Sensitive Data Exposure
  document/4-Web_Application_Security_Testing/01-Information_Gathering/05-Review_Webpage_Comments_and_Metadata_for_Information_Leakage.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/05-Review_Webpage_Content_for_Information_Leakage.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/README.md
  document/README.md
Labels: new

#458 Fix CRLF missed in 441
  .github/workflows/www_latest_update.yml
  .github/workflows/www_stable_update.yml
Labels: repo

#456 Improve LFI text, introduce path truncation bypass & php wrappers
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/11.1-Testing_for_Local_File_Inclusion.md
Labels: revise

#424 corrected Burp extension name
  Testing_for_Horizontal_Bypassing_Authorization_Schema_WSTG-AUTHZ-002.md
Labels: revise

#457 Tweak Wappalyzer References
  document/4-Web_Application_Security_Testing/01-Information_Gathering/08-Fingerprint_Web_Application_Framework.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/09-Fingerprint_Web_Application.md
Labels: revise

#461 Change highlighting hint
  document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
Labels: revise

#462 Add FUNDING.yml for sponsor button
  .github/FUNDING.yml
Labels: repo

#460 Revise CIS-CAT Reference
  document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/02-Test_Application_Platform_Configuration.md
Labels: revise

#472 Add reference and linking details to README
  README.md
Labels: enhancement, integration, revise

#475 Add reference and linking details to Introduction
  document/2-Introduction/README.md
Labels: enhancement, integration, revise

#464 Add other metadata files to 4.1.3
  document/4-Web_Application_Security_Testing/01-Information_Gathering/03-Review_Webserver_Metafiles_for_Information_Leakage.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/images/Meta_Tag_Example-Facebook-Aug_2013.png
Labels: revise

#477 Fix typos in 04-Testing_for_Weak_Encryption.md
  document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/04-Testing_for_Weak_Encryption.md
Labels: bug, revise

#478 Fix HTTP request examples
  document/4-Web_Application_Security_Testing/01-Information_Gathering/09-Fingerprint_Web_Application.md
  document/4-Web_Application_Security_Testing/04-Authentication_Testing/01-Testing_for_Credentials_Transported_over_an_Encrypted_Channel.md
  document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md
  document/4-Web_Application_Security_Testing/06-Session_Management_Testing/03-Testing_for_Session_Fixation.md
  document/4-Web_Application_Security_Testing/06-Session_Management_Testing/04-Testing_for_Exposed_Session_Variables.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/02-Testing_for_Stored_Cross_Site_Scripting.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/03-Testing_for_HTTP_Verb_Tampering.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/04-Testing_for_HTTP_Parameter_Pollution.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05.3-Testing_for_SQL_Server.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/12-Testing_for_Command_Injection.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/14-Testing_for_Incubated_Vulnerability.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/17-Testing_for_Host_Header_Injection.md
  document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/03-Testing_for_Sensitive_Information_Sent_via_Unencrypted_Channels.md
  document/4-Web_Application_Security_Testing/11-Client_Side_Testing/07-Testing_Cross_Origin_Resource_Sharing.md
Labels: revise

#483 Fix 482
  document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/02-Test_Application_Platform_Configuration.md
Labels: revise

#485 Fingerprinting Consolidation
  document/4-Web_Application_Security_Testing/01-Information_Gathering/08-Fingerprint_Web_Application_Framework.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/09-Fingerprint_Web_Application.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/images/wp-syntaxerror.png
Labels: revise
