Repository OWASP/wstg, pull requests merged in 2020-03, with the labels that each got.

#347 Update or remove old www.owasp.org wiki links
  OWASP_Summit_Outcomes.md
  README.md
  document/2_Introduction/2_Introduction.md
  document/3_The_OWASP_Testing_Framework/3.8_Penetration_Testing_Methodologies.md
  document/3_The_OWASP_Testing_Framework/3_The_OWASP_Testing_Framework.md
  document/4_Web_Application_Security_Testing/4.10_Testing_for_Weak_Cryptography/4.10.4_Testing_for_Weak_Encryption_WSTG-CRYPST-004.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.1_Test_Business_Logic_Data_Validation_WSTG-BUSLOGIC-001.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.3_Test_Integrity_Checks_WSTG-BUSLOGIC-003.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.7_Test_Defenses_Against_Application_Mis-use_WSTG-BUSLOGIC-007.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.8_Test_Upload_of_Unexpected_File_Types_WSTG-BUSLOGIC-008.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.9_Test_Upload_of_Malicious_Files_WSTG-BUSLOGIC-009.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.10_Testing_WebSockets_WSTG-CLIENT-010.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.1_Testing_for_DOM-based_Cross_Site_Scripting_WSTG-CLIENT-001.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.2_Testing_for_JavaScript_Execution_WSTG-CLIENT-002.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.4_Testing_for_Client_Side_URL_Redirect_WSTG-CLIENT-004.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.8_Testing_for_Cross_Site_Flashing_WSTG-CLIENT-008.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.9_Testing_for_Clickjacking_WSTG-CLIENT-009.md
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.4_Enumerate_Applications_on_Webserver_WSTG-INFO-004.md
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.9_Fingerprint_Web_Application_WSTG-INFO-009.md
  document/4_Web_Application_Security_Testing/4.3_Configuration_and_Deployment_Management_Testing/4.3.3_Test_File_Extensions_Handling_for_Sensitive_Information_WSTG-CONFIG-003.md
  document/4_Web_Application_Security_Testing/4.3_Configuration_and_Deployment_Management_Testing/4.3.5_Enumerate_Infrastructure_and_Application_Admin_Interfaces_WSTG-CONFIG-005.md
  document/4_Web_Application_Security_Testing/4.3_Configuration_and_Deployment_Management_Testing/4.3.6_Test_HTTP_Methods_WSTG-CONFIG-006.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.3_Testing_for_Weak_Lock_Out_Mechanism_WSTG-AUTHN-003.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.4_Testing_for_Bypassing_Authentication_Schema_WSTG-AUTHN-004.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.7_Testing_for_Weak_Password_Policy_WSTG-AUTHN-007.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.9_Testing_for_Weak_Password_Change_or_Reset_Functionalities_WSTG-AUTHN-009.md
  document/4_Web_Application_Security_Testing/4.6_Authorization_Testing/4.6.4_Testing_for_Insecure_Direct_Object_References_WSTG-AUTHZ-004.md
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.1_Testing_for_Session_Management_Schema_WSTG-SESS-001.md
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.3_Testing_for_Session_Fixation_WSTG-SESS-003.md
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.4_Testing_for_Exposed_Session_Variables_WSTG-SESS-004.md
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.5_Testing_for_CSRF_WSTG-SESS-005.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.10_Testing_for_XPath_Injection_WSTG-INPVAL-010.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.12_Testing_for_Code_Injection_WSTG-INPVAL-012.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.13_Testing_for_Command_Injection_WSTG-INPVAL-013.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.14_Testing_for_Buffer_Overflow_WSTG-INPVAL-014.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.15_Testing_for_Incubated_Vulnerability_WSTG-INPVAL-015.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.16_Testing_for_HTTP_Splitting_Smuggling_WSTG-INPVAL-016.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.19_Testing_for_Server_Side_Template_Injection_WSTG-INPVAL-019.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.1_Testing_for_Reflected_Cross_Site_Scripting_WSTG-INPVAL-001.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.2_Testing_for_Stored_Cross_Site_Scripting_WSTG-INPVAL-002.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.4_Testing_for_HTTP_Parameter_Pollution_WSTG-INPVAL-004.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.5.2_Testing_for_MySQL.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.5.3_Testing_for_SQL_Server.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.5.4_OWASP_Backend_Security_Project_Testing_PostgreSQL.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.5.5_Testing_for_MS_Access.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.5_Testing_for_SQL_Injection_WSTG-INPVAL-005.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.6_Testing_for_LDAP_Injection_WSTG-INPVAL-006.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.8_Testing_for_XML_Injection_WSTG-INPVAL-008.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.9_Testing_for_SSI_Injection_WSTG-INPVAL-009.md
  document/4_Web_Application_Security_Testing/4.9_Testing_for_Error_Handling/4.9.1_Testing_for_Error_Code_WSTG-ERR-001.md
  document/Appx.A_Testing_Tools_Resource/Appx.A_Testing_Tools.md
  document/Appx.B_Suggested_Reading/Appx.B_Suggested_Reading.md
  document/Appx.C_Fuzz_Vectors/Appx.C_Fuzz_Vectors.md
  template/999.2_Template_Explanation_WSTG-FOO-002.md
Labels: revise

#345 Redo Section 1 Tweak Section 0
  document/0_Foreword/0_Foreword.md
  document/1_Frontispiece/1.2_About_The_Open_Web_Application_Security_Project.md
  document/1_Frontispiece/1_Frontispiece.md
Labels: revise

#373 Fixing sentences and sources
  Testing_for_Vertical_Bypassing_Authorization_Schema_WSTG-AUTHZ-00X.md
Labels: revise

#378 Updated formatting error on 4.5.1: Testing for Credentials Transported over an Encrypted Channel
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.1_Testing_for_Credentials_Transported_over_an_Encrypted_Channel_WSTG-AUTHN-001.md
Labels: revise

#375 Fix ToC
  document/README.md
Labels: bug, revise

#362 Add SameSite to cookie attributes
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.2_Testing_for_Cookies_Attributes_WSTG-SESS-002.md
Labels: revise

#377 Tweak Appendix E history details and contributor info
  document/1_Frontispiece/1_Frontispiece.md
  document/Appx.E_Misc/Appx.E_History.md
Labels: revise

#382 Update Link Check Action
  .github/workflows/dummy.yml
  .github/workflows/md-link-check.yml
Labels: repo

#372 add attack surface detector, with small changes regarding methods for…
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.6_Identify_Application_Entry_Points_WSTG-INFO-006.md
Labels: revise

#348 Update client side storage document
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.12_Testing_Web_Storage.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/images/Storage-xss.png
Labels: revise

#392 Fix 270 - Rewrite ORM Injection
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.10_Testing_for_XPath_Injection.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.11_Testing_for_IMAP_SMTP_Injection.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.12_Testing_for_Code_Injection.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.13_Testing_for_Command_Injection.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.14_Testing_for_Buffer_Overflow.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.15_Testing_for_Incubated_Vulnerability.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.16_Testing_for_HTTP_Splitting_Smuggling.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.17_Testing_for_HTTP_Incoming_Requests.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.18_Testing_for_Host_Header_Injection.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.19_Testing_for_Server_Side_Template_Injection.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.5.7_Testing_for_ORM_Injection.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.7_Testing_for_ORM_Injection.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.8_Testing_for_XML_Injection.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.9_Testing_for_SSI_Injection.md
Labels: revise

#349 Fix 272 - Template Structure and Client Side SQLi
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.5.8_Testing_for_Client-Side.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.5_Testing_for_SQL_Injection.md
Labels: revise

#394 4.9.5 Remove misleading examples
  document/4-Web_Application_Security_Testing/01-Information_Gathering/05-Review_Webpage_Comments_and_Metadata_for_Information_Leakage.md
Labels: revise

#393 Add traffic capture/sniffing tools
  document/4-Web_Application_Security_Testing/04-Authentication_Testing/01-Testing_for_Credentials_Transported_over_an_Encrypted_Channel.md
  document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
  document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/03-Testing_for_Sensitive_Information_Sent_via_Unencrypted_Channels.md
Labels: revise

#397 Tweak minor naming issue
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05.7-Testing_for_ORM_Injection.md
  document/README.md
Labels: bug

#396 Add more references - Testing Business Logic Data Validation
  document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/01-Test_Business_Logic_Data_Validation.md
Labels: revise

#399 Minor - Linkify DDo$
  document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/01-Test_Business_Logic_Data_Validation.md
Labels: revise

#400 Remove "content" from ToC
  document/README.md
Labels: revise

#401 Tweak Headings to Title Caps
  document/3-The_OWASP_Testing_Framework/1-Penetration_Testing_Methodologies.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/11.2-Testing_for_Remote_File_Inclusion.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/14-Testing_for_Incubated_Vulnerability.md
  document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md
  document/4-Web_Application_Security_Testing/11-Client_Side_Testing/09-Testing_for_Clickjacking.md
  document/Appx.C_Fuzz_Vectors/README.md
Labels: bug, revise
