Repository OWASP/wstg, pull requests merged in 2020-08, with the labels that each got.

#534 Implement pull_request_target for link checking
  .github/workflows/md-link-check.yml
Labels: enhancement, repo

#545 MiTM tweaks
  .textlintrc
  document/2-Introduction/README.md
  document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/07-Test_HTTP_Strict_Transport_Security.md
  document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection.md
Labels: enhancement, repo

#537 textlint: Further allow/deny list handling
  .textlintrc
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/01-Testing_for_Reflected_Cross_Site_Scripting.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/11.2-Testing_for_Remote_File_Inclusion.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/18-Testing_for_Server-side_Template_Injection.md
  document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/08-Test_Upload_of_Unexpected_File_Types.md
Labels: enhancement, repo, revise

#547 Support GitHub Codespaces
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  CONTRIBUTING.md
  README.md
Labels: enhancement, repo

#501 Added dev tools testing info
  document/6-Appendix/F-Leveraging_Dev_Tools.md
  document/6-Appendix/README.md
  document/6-Appendix/images/f_chrome_devtools_headers.png
  document/6-Appendix/images/f_chrome_devtools_offline.png
  document/6-Appendix/images/f_chrome_devtools_ua_switch.png
  document/6-Appendix/images/f_chrome_responsive_design_mode.png
  document/6-Appendix/images/f_firefox_cookie_edit.png
  document/6-Appendix/images/f_firefox_devtools_headers.png
  document/6-Appendix/images/f_firefox_devtools_offline.png
  document/6-Appendix/images/f_firefox_responsive_design_mode.png
  document/6-Appendix/images/f_firefox_ua_switch.png
  document/README.md
Labels: revise

#550 Typo Fix (caps mistake)
  document/6-Appendix/F-Leveraging_Dev_Tools.md
Labels: bug, revise

#548 4 - Intro and Info Gathering Content Review
  document/4-Web_Application_Security_Testing/00-Introduction_and_Objectives/README.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/01-Conduct_Search_Engine_Discovery_Reconnaissance_for_Information_Leakage.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/06-Identify_Application_Entry_Points.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/07-Map_Execution_Paths_Through_Application.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/10-Map_Application_Architecture.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/images/10_mod_security.jpg
  markdown-link-check-config.json
Labels: revise
