Repository OWASP/wstg, pull requests merged in 2020-11, with the labels that each got.

#604 CRYP-04 Edits
  document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/04-Testing_for_Weak_Encryption.md
Labels: revise

#606 Update to address in-line references
  style_guide.md
Labels: repo

#608 Update contribution info following root cleanup
  .devcontainer/devcontainer.json
  .gitignore
  CONTRIBUTING.md
Labels: repo

#610 Accommodate breadcrumb include in latest deployment(s)
  .github/www/latest/prepend.txt
Labels: repo

#611 Revise HSTS Scenario
  .github/configs/.textlintrc
  document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/07-Test_HTTP_Strict_Transport_Security.md
  document/4-Web_Application_Security_Testing/03-Identity_Management_Testing/04-Testing_for_Account_Enumeration_and_Guessable_User_Account.md
  document/4-Web_Application_Security_Testing/06-Session_Management_Testing/01-Testing_for_Session_Management_Schema.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05.2-Testing_for_MySQL.md
  document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/06-Testing_for_the_Circumvention_of_Work_Flows.md
Labels: revise

#612 MD004 Dashes throughout
  .github/configs/.markdownlint.json
  document/2-Introduction/README.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/05-Review_Webpage_Content_for_Information_Leakage.md
  document/4-Web_Application_Security_Testing/05-Authorization_Testing/01-Testing_Directory_Traversal_File_Include.md
  document/4-Web_Application_Security_Testing/06-Session_Management_Testing/03-Testing_for_Session_Fixation.md
  document/4-Web_Application_Security_Testing/06-Session_Management_Testing/05-Testing_for_Cross_Site_Request_Forgery.md
  document/4-Web_Application_Security_Testing/06-Session_Management_Testing/09-Testing_for_Session_Hijacking.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/13-Testing_for_Format_String_Injection.md
  document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/00-Introduction_to_Business_Logic.md
Labels: repo

#616 Fix image tag formatting issues
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/10-Testing_WebSockets.md
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/13-Testing_for_Cross_Site_Script_Inclusion.md
  document/6-Appendix/F-Leveraging_Dev_Tools.md
  style_guide.md
Labels: bug, revise

#617 Fix broken TOC in last appendix entry (PDF Build)
  .github/pdf/scripts/make-pdf.sh
Labels: bug, revise

#631 Fix link issues in PDF build 4.2
  .github/pdf/scripts/make-pdf.sh
  document/4-Web_Application_Security_Testing/12-API_Testing/01-Testing_GraphQL.md
  document/6-Appendix/F-Leveraging_Dev_Tools.md
Labels: bug, repo
