Repository OWASP/wstg, pull requests merged in 2020-02, with the labels that each got.

#259 Add the section 'Testing for Special Request Header Handling'
  document/4_Web_Application_Security_Testing/4.6_Authorization_Testing/4.6.2_Testing_for_Bypassing_Authorization_Schema_OTG-AUTHZ-002.md
Labels: new

#314 Update sample article
  template/999.1_Testing_for_a_Cat_in_a_Box_OTG-FOO-001.md
Labels: repo

#323 Issue 152: Remove Webscarab Reference
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.13_Testing_for_Command_Injection_WSTG-INPVAL-013.md
Labels: revise

#326 Fix owasp.org links and link internally
  document/4_Web_Application_Security_Testing/4.10_Testing_for_Weak_Cryptography/4.10.1_Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection_WSTG-CRYPST-001.md
  document/4_Web_Application_Security_Testing/4.10_Testing_for_Weak_Cryptography/4.10.3_Testing_for_Sensitive_Information_Sent_via_Unencrypted_Channels_WSTG-CRYPST-003.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.1_Test_Business_Logic_Data_Validation_WSTG-BUSLOGIC-001.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.2_Test_Ability_to_Forge_Requests_WSTG-BUSLOGIC-002.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.4_Test_for_Process_Timing_WSTG-BUSLOGIC-004.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.6_Testing_for_the_Circumvention_of_Work_Flows_WSTG-BUSLOGIC-006.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.8_Test_Upload_of_Unexpected_File_Types_WSTG-BUSLOGIC-008.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.9_Test_Upload_of_Malicious_Files_WSTG-BUSLOGIC-009.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.10_Testing_WebSockets_WSTG-CLIENT-010.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.15_Testing_for_Incubated_Vulnerability_WSTG-INPVAL-015.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.5.2_Testing_for_MySQL.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.5.4_OWASP_Backend_Security_Project_Testing_PostgreSQL.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.5.6_Testing_for_NoSQL_Injection.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.7_Testing_for_ORM_Injection_WSTG-INPVAL-007.md
  document/4_Web_Application_Security_Testing/4.9_Testing_for_Error_Handling/4.9.1_Testing_for_Error_Code_WSTG-ERR-001.md
Labels: revise

#327 Move End-links or Footer References to in-line links
  document/4_Web_Application_Security_Testing/4.10_Testing_for_Weak_Cryptography/4.10.1_Testing_for_Weak_SSL_TLS_Ciphers_Insufficient_Transport_Layer_Protection_WSTG-CRYPST-001.md
  document/4_Web_Application_Security_Testing/4.10_Testing_for_Weak_Cryptography/4.10.3_Testing_for_Sensitive_Information_Sent_via_Unencrypted_Channels_WSTG-CRYPST-003.md
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.10_Map_Application_Architecture_WSTG-INFO-010.md
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.3_Review_Webserver_Metafiles_for_Information_Leakage_WSTG-INFO-003.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.3_Testing_for_HTTP_Verb_Tampering_WSTG-INPVAL-003.md
Labels: revise

#325 Fix 324
  document/4_Web_Application_Security_Testing/4.3_Configuration_and_Deployment_Management_Testing/4.3.9_Test_File_Permission_WSTG-CONFIG-009.md
Labels: revise

#330 Further link updates
  document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.7_Map_Execution_Paths_Through_Application_WSTG-INFO-007.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.14.3_Testing_for_Format_String.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.15_Testing_for_Incubated_Vulnerability_WSTG-INPVAL-015.md
Labels: revise

#316 Implement link checker in Github Actions (CI)
  .github/workflows/md-link-check.yml
  markdown-link-check-config.json
  package.json
Labels: repo

#329 New 4.3.11 test cloud storage (mainly on Amazon S3)
  document/4_Web_Application_Security_Testing/4.3_Configuration_and_Deployment_Management_Testing/4.3.11_Test_Cloud_Storage_WSTG-CONFIG-011.md
Labels: new

#337 Update ZAP References
  document/2_Introduction/2_Introduction.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.1_Test_Business_Logic_Data_Validation_WSTG-BUSLOGIC-001.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.2_Test_Ability_to_Forge_Requests_WSTG-BUSLOGIC-002.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/4.11.3_Test_Integrity_Checks_WSTG-BUSLOGIC-003.md
  document/4_Web_Application_Security_Testing/4.11_Business_Logic_Testing/README.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.10_Testing_WebSockets_WSTG-CLIENT-010.md
  document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.7_Testing_Cross_Origin_Resource_Sharing_WSTG-CLIENT-007.md
  document/4_Web_Application_Security_Testing/4.4_Identity_Management_Testing/4.4.4_Testing_for_Account_Enumeration_and_Guessable_User_Account_WSTG-IDENT-004.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.4_Testing_for_Bypassing_Authentication_Schema_WSTG-AUTHN-004.md
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.6_Testing_for_Browser_Cache_Weaknesses_WSTG-AUTHN-006.md
  document/4_Web_Application_Security_Testing/4.6_Authorization_Testing/4.6.3_Testing_for_Privilege_Escalation_WSTG-AUTHZ-003.md
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.1_Testing_for_Session_Management_Schema_WSTG-SESS-001.md
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.2_Testing_for_Cookies_Attributes_WSTG-SESS-002.md
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.3_Testing_for_Session_Fixation_WSTG-SESS-003.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.1_Testing_for_Reflected_Cross_Site_Scripting_WSTG-INPVAL-001.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.2_Testing_for_Stored_Cross_Site_Scripting_WSTG-INPVAL-002.md
  document/4_Web_Application_Security_Testing/4.8_Input_Validation_Testing/4.8.4_Testing_for_HTTP_Parameter_Pollution_WSTG-INPVAL-004.md
  document/4_Web_Application_Security_Testing/4.9_Testing_for_Error_Handling/4.9.1_Testing_for_Error_Code_WSTG-ERR-001.md
  document/4_Web_Application_Security_Testing/4.9_Testing_for_Error_Handling/4.9.2_Testing_for_Stack_Traces_WSTG-ERR-002.md
  document/Appx.A_Testing_Tools_Resource/Appx.A_Testing_Tools.md
  document/Appx.C_Fuzz_Vectors/Appx.C_Fuzz_Vectors.md
Labels: revise

#336 Revise Link Check Action
  .github/workflows/md-link-check.yml
  package.json
Labels: repo

#335 Fix Style Guide References
  template/999.2_Template_Explanation_WSTG-FOO-002.md
Labels: bug, repo

#333 Revise CSRF section
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.5_Testing_for_CSRF_WSTG-SESS-005.md
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/images/Session_Riding_Firewall_Management.gif
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/images/Session_Riding_Firewall_Management_2.gif
  document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/images/Session_riding.GIF
Labels: revise

#341 Link Checker: remove push inclusion
  .github/workflows/md-link-check.yml
Labels: bug, repo

#338 Update 4.5.6 (browser cache) for new browsers and OS
  document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.6_Testing_for_Browser_Cache_Weaknesses_WSTG-AUTHN-006.md
Labels: revise
