Repository OWASP/wstg, pull requests merged in 2020-12, with the labels that each got.

#642 Checklist Pre-v4.2
  checklist/Testing_Checklist.md
  document/4-Web_Application_Security_Testing/04-Authentication_Testing/06-Testing_for_Browser_Cache_Weaknesses.md
  document/5-Reporting/README.md
Labels: enhancement, revise

#646 Update Credits for 4.2
  document/1-Frontispiece/README.md
Labels: revise

#652 Update frontispiece
  document/1-Frontispiece/README.md
Labels: revise

#653 Fix ENV var setting
  .github/workflows/www_stable_update.yml
Labels: repo

#655 Tweak .gitignore
  .gitignore
Labels: repo

#675 Update 10-Test_for_Subdomain_Takeover.md
  document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/10-Test_for_Subdomain_Takeover.md
Labels: enhancement

#679 Tweak Classic SQLi section
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05-Testing_for_SQL_Injection.md
Labels: revise
