Repository OWASP/wstg, pull requests merged in 2021-03, with the labels that each got.

#709 Add certificates as an information gathering technique to find vhosts
  document/4-Web_Application_Security_Testing/01-Information_Gathering/04-Enumerate_Applications_on_Webserver.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/images/Owasp-Info.jpg
Labels: help wanted

#724 Rework Contribution Guidance for Translations
  CONTRIBUTING.md
  translations/es/0-Foreword/README.md
  translations/es/3-The_OWASP_Testing_Framework/0-The_Web_Security_Testing_Framework.md
  translations/es/3-The_OWASP_Testing_Framework/1-Penetration_Testing_Methodologies.md
  translations/es/3-The_OWASP_Testing_Framework/README.md
Labels: repo

#726 Add Portuguese-BR translation repo link
  CONTRIBUTING.md
Labels: Translation

#714 Merge ATHN-01 into CRYP-03
  document/4-Web_Application_Security_Testing/04-Authentication_Testing/01-Testing_for_Credentials_Transported_over_an_Encrypted_Channel.md
  document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/03-Testing_for_Sensitive_Information_Sent_via_Unencrypted_Channels.md
Labels: revise
