Repository OWASP/wstg, pull requests merged in 2021-06, with the labels that each got.

#759 chore: www publishing workflows now use static feature branch names
  .github/workflows/www_latest_update.yml
  .github/workflows/www_stable_update.yml
Labels: repo

#664 remove Gray-box and code-review sections from 4.1 information gathering
  document/4-Web_Application_Security_Testing/01-Information_Gathering/06-Identify_Application_Entry_Points.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/07-Map_Execution_Paths_Through_Application.md
Labels: help wanted

#761 improve: GitHub Action Workflows no longer include file ext on links
  .github/workflows/www_latest_update.yml
  .github/workflows/www_stable_update.yml
Labels: repo

#762 fix: GitHub Action Workflows no longer include file ext on links
  .github/workflows/www_latest_update.yml
  .github/workflows/www_stable_update.yml
Labels: repo

#757 Various grammar and format tweaks
  README.md
  Testing_for_APIs.md
  checklist/Testing_Checklist.md
  document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy.md
  template/999-Foo_Testing/3-Format_for_HTTP_Request_Response.md
Labels: revise
