Repository OWASP/wstg, pull requests merged in 2021-07, with the labels that each got.

#765 Change stale to 90d
  .github/workflows/refresh-stale.yml
Labels: repo, revise

#768 Update Latest - Only commit/PR if there are changes
  .github/workflows/www_latest_update.yml
Labels: enhancement, repo

#769 Tweak Resource Files
  .gitattributes
  .github/www/latest/prepend.nav
  .github/www/stable/prepend.nav
  .github/www/v41/prepend.nav
Labels: repo, revise

#770 Add files before checking for changes
  .github/workflows/www_latest_update.yml
Labels: repo

#777 fix: link check exclusions now include github
  .github/configs/markdown-link-check-config.json
Labels: repo

#713 ADD Self DOM Based Cross Site Scripting Testing #269
  checklist/Testing_Checklist.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Self_DOM_Based_Cross_Site_Scripting.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/README.md
  document/README.md
Labels: new
