Repository OWASP/wstg, pull requests merged in 2022-03, with the labels that each got.

#859 Add missing article in sentences
  document/4-Web_Application_Security_Testing/01-Information_Gathering/03-Review_Webserver_Metafiles_for_Information_Leakage.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/04-Enumerate_Applications_on_Webserver.md
Labels: revise

#853 Update HTTP method testing.
  document/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/06-Test_HTTP_Methods.md
Labels: revise

#861 Remove Broken Link From #References
  document/4-Web_Application_Security_Testing/03-Identity_Management_Testing/04-Testing_for_Account_Enumeration_and_Guessable_User_Account.md
Labels: revise

#869 chore: Upgrade lint workflows to node 16
  .github/workflows/md-link-check.yml
  .github/workflows/md-lint-check.yml
  .github/workflows/md-textlint-check.yml
Labels: repo

#874 Update make-json.sh use latest not stable
  .github/scripts/make-json.sh
Labels: revise, repo

#866 chore: Text Lint Additions
  .github/configs/.textlintrc
  document/4-Web_Application_Security_Testing/01-Information_Gathering/04-Enumerate_Applications_on_Webserver.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/10-Map_Application_Architecture.md
  document/4-Web_Application_Security_Testing/04-Authentication_Testing/02-Testing_for_Default_Credentials.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/13-Testing_for_Format_String_Injection.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/17-Testing_for_Host_Header_Injection.md
  document/4-Web_Application_Security_Testing/11-Client-side_Testing/09-Testing_for_Clickjacking.md
  package.json
Labels: enhancement, revise, repo

#888 Fix "senstive" Typo
  document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/03-Testing_for_Sensitive_Information_Sent_via_Unencrypted_Channels.md
Labels: revise
