Repository OWASP/wstg, pull requests merged in 2022-09, with the labels that each got.

#969 Update 01-Reporting_Structure.md
  document/5-Reporting/01-Reporting_Structure.md
Labels: bug, revise

#966 965 workflow linters update version
  .github/workflows/md-link-check.yml
  .github/workflows/md-textlint-check.yml
Labels: repo

#972 chore: Lint workflows use changed files v4 and undo translation bits
  .github/workflows/md-link-check.yml
  .github/workflows/md-textlint-check.yml
Labels: repo

#973 docs: clarify samesite attribute
  document/4-Web_Application_Security_Testing/06-Session_Management_Testing/02-Testing_for_Cookies_Attributes.md
Labels: revise
