Repository OWASP/wstg, pull requests merged in 2022-12, with the labels that each got.

#995 List Translation efforts in main README
  CONTRIBUTING.md
  README.md
Labels: repo

#993 Upload XLSX template to Google Drive
  .github/workflows/build-checklists.yml
  .github/xlsx/scripts/create-google-drive-cred.py
  .github/xlsx/scripts/upload-to-google-drive.py
  checklists/README.md
  package.json
Labels: enhancement, repo

#994 chore: Add PDF cover page for v4.3
  .github/pdf/assets/cover-v4.3.jpg
Labels: repo

#998 chore: Update github action dependencies to the latest versions
  .github/workflows/build-checklists.yml
  .github/workflows/md-link-check.yml
  .github/workflows/md-lint-check.yml
  .github/workflows/md-textlint-check.yml
Labels: repo

#996 chore: PDF build - Add design to Vuln ID, fix blank page and wrong bookmark issue
  .github/pdf/assets/cover.jpg
  .github/pdf/assets/pdf-style.css
  .github/pdf/pdf-config.json
  .github/pdf/scripts/make-pdf.sh
  .github/workflows/build-pdf.yml
  package.json
Labels: repo

#1000 chore: EPUB build action
  .github/epub/README.md
  .github/epub/assets/epub-style.css
  .github/epub/scripts/make-epub.sh
  .github/workflows/README.md
  .github/workflows/build-ebooks.yml
  package.json
Labels: repo

#1001 Update scenario with no domain attribute
  document/4-Web_Application_Security_Testing/06-Session_Management_Testing/02-Testing_for_Cookies_Attributes.md
Labels: revise

#1004 workflows: Fix actions/github-script createComment usage
  .github/workflows/md-link-check.yml
  .github/workflows/md-lint-check.yml
  .github/workflows/md-textlint-check.yml
Labels: revise, repo
