Repository OWASP/wstg, pull requests merged in 2023-05, with the labels that each got.

#1044 Update Suggested Reading with most recent document link
  document/6-Appendix/B-Suggested_Reading.md
Labels: revise

#1045 Fix markdown lint issues
  CODE_OF_CONDUCT.md
  document/4-Web_Application_Security_Testing/06-Session_Management_Testing/01-Testing_for_Session_Management_Schema.md
  document/4-Web_Application_Security_Testing/06-Session_Management_Testing/04-Testing_for_Exposed_Session_Variables.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05-Testing_for_SQL_Injection.md
  document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05.6-Testing_for_NoSQL_Injection.md
Labels: revise, repo

#1050 Upgrade Changed FIles to 4.0.1
  .github/workflows/md-link-check.yml
  .github/workflows/md-textlint-check.yml
Labels: repo

#1053 Update 05-Review_Web_Page_Content_for_Information_Leakage.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/05-Review_Web_Page_Content_for_Information_Leakage.md
Labels: revise

#1054 fix: Link Check Workflow
  .github/workflows/md-link-check.yml
Labels: repo

#1061 Addressed informal tone and improved readability
  document/4-Web_Application_Security_Testing/01-Information_Gathering/07-Map_Execution_Paths_Through_Application.md
  document/4-Web_Application_Security_Testing/01-Information_Gathering/08-Fingerprint_Web_Application_Framework.md
Labels: revise
